server:
  port: 8083

spring:
  application:
    name: pay-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://111.229.40.252:3306/pay
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ccssoft.start.entities

eureka:
  client:
    register-with-eureka: true #是否向服务中心注册自己
    fetch-registry: true #是否从EurekaServer中查询已注册的服务
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka #集群版
  instance:
    instance-id: pay8003 #修改微服务显示的机器名称
    prefer-ip-address: true #是否显示微服务IP地址